### ISSUE TITLE
Получение operations выбрасывает исключение

### ISSUE THREAD

**Issue by xkrt** [TinkoffCreditSystems/invest-openapi-java-sdk#10]
Привет,

Код падает с исключением:
```scala
var connection = ConnectionFactory.connect(token, sdkLogger).join()
var context = connection.context();
var operations = context.getOperations(LocalDate.parse("2019-09-01"), OperationInterval.MONTH, "").join()
```

Exception:
```
Exception in thread "main" java.util.concurrent.CompletionException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token
 at [Source: (String)"{"trackingId":"451a9dd77b00f414","payload":{"operations":[]},"status":"Ok"}"; line: 1, column: 44] (through reference chain: ru.tinkoff.trading.openapi.data.OpenApiResponse["payload"])
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:840)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token
 at [Source: (String)"{"trackingId":"451a9dd77b00f414","payload":{"operations":[]},"status":"Ok"}"; line: 1, column: 44] (through reference chain: ru.tinkoff.trading.openapi.data.OpenApiResponse["payload"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
	at ru.tinkoff.trading.openapi.wrapper.impl.ContextImpl.handleResponse(ContextImpl.java:228)
	at ru.tinkoff.trading.openapi.wrapper.impl.ContextImpl.lambda$sendGetRequest$14(ContextImpl.java:195)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
```

При этом запрос с этими параметрами нормально отрабатывает через Swagger и возвращает данные. По тексту ошибки кажется, что вернулся пустой массив операций.
Вызов получения состава портфеля при этом работает нормально.

**Comment by NikitaMelnikov** [comment]
А если запросить операции за дату, когда они были, то все работает?

**Comment by zlumyo** [comment]
@NikitaMelnikov выявил расхождение между моделью ответа в swagger и тем, что реально возвращается в json. Похоже надо поправить само API.

**Comment by NikitaMelnikov** [comment]
Поправим документацию

**Comment by NikitaMelnikov** [comment]
https://api-invest.tinkoff.ru/openapi/docs/swagger-ui/index.html#/operations/get_operations
Поправили документацию

@zlumyo в 0.2 поменяешь протокол?

**Comment by zlumyo** [comment]
@NikitaMelnikov сделал отдельный ПР под 0.1.1, чтобы 0.1 версия была не битой

**Comment by NikitaMelnikov** [comment]
Смержил
