### ISSUE TITLE
При инициализации соединения  - 423 Locked

### ISSUE THREAD

**Issue by Sherlit** [TinkoffCreditSystems/invest-openapi-java-sdk#105]
При инициализации соединения в примере из библиотеки, получаю ответ "423 Locked"

[2020-10-11 21:55:54.974] [INFO   ] ru.tinkoff.tradingBot.App main 
Создаём подключение... 
[2020-10-11 21:56:11.978] [SEVERE ] ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure 
Что-то произошло в Streaming API клиенте #1
java.net.ProtocolException: Expected HTTP 101 response but was '423 Locked'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:185)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:156)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by NikitaMelnikov** [comment]
Вероятно вы создаете больше 6 одновременных подключений

**Comment by stalexxx** [comment]
> Вероятно вы создаете больше 6 одновременных подключений

Вероятно, это прописано в вашем конфиге без возможности это изменить

**Comment by leodev87** [comment]
> > Вероятно вы создаете больше 6 одновременных подключений
> 
> Вероятно, это прописано в вашем конфиге без возможности это изменить

Религия не позволяет переписать в конфиге?

**Comment by zlumyo** [comment]
Да, вы можете переопределить значение в конфигурационном файле, если это необходимо.
