### ISSUE TITLE
Попытка восстановления Streaming API клиента #

### ISSUE THREAD

**Issue by felixrap** [TinkoffCreditSystems/invest-openapi-java-sdk#63]
При запуске куска кода из Example 
   var api =  fac.createOpenApiClient(se -> logger.info("stream up"),
                    ex -> logger.severe("stream drop"));
   api.marketContext.getMarketBonds().join();

получаю в логах:

INFO: Логгер запущен
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #5 подключён
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #1 подключён
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #4 подключён
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #6 подключён
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #3 подключён
февр. 12, 2020 7:37:13 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #2 подключён
февр. 12, 2020 7:37:14 PM okhttp3.internal.platform.Platform log
INFO: Callback failure for call to https://api-invest.tinkoff.ru/...
com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'type' (index 7)
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 225] (through reference chain: ru.tinkoff.invest.openapi.models.RestResponse["payload"]->ru.tinkoff.invest.openapi.models.market.InstrumentsList["instruments"]->java.util.ArrayList[0]->ru.tinkoff.invest.openapi.models.market.Instrument["type"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer._findMissing(PropertyValueBuffer.java:194)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.getParameters(PropertyValueBuffer.java:160)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3250)
	at ru.tinkoff.invest.openapi.okhttp.BaseContextImpl.handleResponse(BaseContextImpl.java:72)
	at ru.tinkoff.invest.openapi.okhttp.MarketContextImpl$6.onResponse(MarketContextImpl.java:98)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #4
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #4
февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #6
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #6
февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #5
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #5
февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #3
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #3
февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #2
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #2
февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #1
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:14 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #1
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #4 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #6 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #5 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #3 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #1 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #2 активно 0 подписок
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #1 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #2 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #4 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #6 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #3 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #5 подключён
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #2
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #2
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #1
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #1
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #5
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #5
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #4
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #4
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #6
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #6
февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #3
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:15 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #3
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #2 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #1 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #5 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #4 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #6 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: У клиента #3 активно 0 подписок
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #1 подключён
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #5 подключён
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onOpen
INFO: Streaming API клиент #2 подключён
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #6
java.net.ProtocolException: Expected HTTP 101 response but was '429 Too Many Requests'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:185)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:156)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #6
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #3
java.net.ProtocolException: Expected HTTP 101 response but was '429 Too Many Requests'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:185)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:156)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #3
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #4
java.net.ProtocolException: Expected HTTP 101 response but was '429 Too Many Requests'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:185)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:156)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #4
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #2
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #5
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #5
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #2
февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
SEVERE: Что-то произошло в Streaming API клиенте #1
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:240)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

февр. 12, 2020 7:37:16 PM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl restore
INFO: Попытка восстановления Streaming API клиента #1

**Comment by zlumyo** [comment]
@felixrap похоже само API стало не соответствовать заявленному в swagger протоколу. Я уведомил коллег об этом случае, но на будущее подобные общие вопросы можно задавать в [главном репозитории](https://github.com/TinkoffCreditSystems/invest-openapi).
